# Generated by Django 5.2.17 on 2026-09-10 08:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(default='Equipment', max_length=40)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('acquired_on', models.DateField(default=django.utils.timezone.localdate)),
                ('location', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('bank', models.CharField(max_length=80)),
                ('number', models.CharField(max_length=40, unique=True)),
                ('opening', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Nexora Demo Stores', max_length=160)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('vat_number', models.CharField(blank=True, max_length=40)),
                ('currency', models.CharField(default='BDT', max_length=8)),
                ('default_vat', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('language', models.CharField(default='en', max_length=8)),
                ('theme', models.CharField(default='void', max_length=16)),
                ('point_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Loyalty points earned per 100 spent.', max_digits=6)),
                ('point_value', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Taka value of one loyalty point.', max_digits=6)),
            ],
            options={
                'verbose_name_plural': 'company',
            },
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('kind', models.CharField(choices=[('office', 'Office'), ('fixed', 'Fixed'), ('other', 'Other')], default='office', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('share_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sku', models.CharField(max_length=40, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(unique=True)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('to', models.CharField(max_length=24)),
                ('body', models.CharField(max_length=480)),
                ('status', models.CharField(choices=[('q', 'Queued'), ('s', 'Sent'), ('f', 'Failed')], default='s', max_length=2)),
                ('kind', models.CharField(default='notice', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('code', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=120)),
                ('bytes', models.PositiveIntegerField(default=0)),
                ('tables', models.PositiveIntegerField(default=0)),
                ('rows', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=30)),
                ('payee', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issued_on', models.DateField(default=django.utils.timezone.localdate)),
                ('cleared_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='issued', max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='core.bankaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_wholesale', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('kind', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customertype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('designation', models.CharField(blank=True, max_length=80)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('joined_on', models.DateField(default=django.utils.timezone.localdate)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('incurred_on', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('is_fixed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.expensehead')),
            ],
            options={
                'ordering': ['-incurred_on'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('in', 'Investment'), ('out', 'Withdraw')], max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('booked_on', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.CharField(blank=True, max_length=160)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='core.investor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=24, unique=True)),
                ('kind', models.CharField(choices=[('recv', 'Receive'), ('pay', 'Payment'), ('cxfer', 'Cash transfer'), ('bcash', 'Bank to cash'), ('exp', 'Expense'), ('sal', 'Salary'), ('inv', 'Investment'), ('wdr', 'Invest withdraw'), ('sale', 'Sale receipt'), ('pur', 'Purchase payment')], max_length=8)),
                ('direction', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('counterparty', models.CharField(blank=True, max_length=160)),
                ('reference', models.CharField(blank=True, max_length=40)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('booked_on', models.DateField(default=django.utils.timezone.localdate)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='core.bankaccount')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booked_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PointLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('delta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=80)),
                ('reference', models.CharField(blank=True, max_length=40)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_rows', to='core.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=40, unique=True)),
                ('barcode', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('min_stock', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=12)),
                ('warranty_months', models.PositiveSmallIntegerField(default=0)),
                ('stock_mode', models.CharField(choices=[('owned', 'Owned stock'), ('consign', 'After-sell supplier stock')], default='owned', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('is_service', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.package')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=24, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('done', 'Completed'), ('due', 'Due'), ('ret', 'Returned'), ('void', 'Void')], default='done', max_length=8)),
                ('channel', models.CharField(choices=[('pos', 'POS'), ('online', 'Online order'), ('whole', 'Wholesale')], default='pos', max_length=8)),
                ('sold_on', models.DateField(default=django.utils.timezone.localdate)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('paid_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('bkash_trx', models.CharField(blank=True, max_length=40)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='core.customer')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.shop')),
            ],
            options={
                'ordering': ['-sold_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OnlineOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=24, unique=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('ok', 'Confirmed'), ('pack', 'Packed'), ('ship', 'Shipped'), ('done', 'Delivered'), ('cx', 'Cancelled')], default='new', max_length=8)),
                ('address', models.CharField(max_length=240)),
                ('phone', models.CharField(max_length=24)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.customer')),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_order', to='core.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=24, unique=True)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('down_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('months', models.PositiveSmallIntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('started_on', models.DateField(default=django.utils.timezone.localdate)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='core.customer')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installment', to='core.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommissionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='core.employee')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='core.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bkash', 'bKash'), ('card', 'Card'), ('bank', 'Bank'), ('due', 'Due'), ('mixed', 'Mixed'), ('points', 'Loyalty points')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('received_on', models.DateField(default=django.utils.timezone.localdate)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('code', models.SlugField()),
                ('kind', models.CharField(choices=[('counter', 'POS counter'), ('warehouse', 'Warehouse'), ('godown', 'Godown'), ('online', 'Online')], default='counter', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='core.shop')),
            ],
            options={
                'unique_together': {('shop', 'code')},
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.station'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('accountant', 'Accountant'), ('store', 'Storekeeper'), ('hr', 'HR')], default='cashier', max_length=16)),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('language', models.CharField(default='en', max_length=8)),
                ('theme', models.CharField(default='void', max_length=16)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.shop')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.station')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.station'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField()),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='core.category')),
            ],
            options={
                'verbose_name_plural': 'sub-categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.subcategory'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=24, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Request'), ('ordered', 'Ordered'), ('received', 'Received'), ('partial', 'Part received'), ('returned', 'Returned'), ('void', 'Cancelled')], default='draft', max_length=10)),
                ('ordered_on', models.DateField(default=django.utils.timezone.localdate)),
                ('received_on', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='core.station')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='core.supplier')),
            ],
            options={
                'ordering': ['-ordered_on', '-id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='consign_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consign_products', to='core.supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.unittype'),
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
                ('object_id', models.CharField(blank=True, max_length=40)),
                ('detail', models.CharField(blank=True, max_length=240)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard', max_length=80)),
                ('sku', models.CharField(max_length=40, unique=True)),
                ('barcode', models.CharField(max_length=40, unique=True)),
                ('extra_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=24, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='core.purchase')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.variant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=24, unique=True)),
                ('kind', models.CharField(choices=[('in', 'Stock in'), ('out', 'Stock out'), ('transfer', 'Transfer'), ('sale', 'Sale'), ('sret', 'Sale return'), ('pur', 'Purchase receive'), ('pret', 'Supplier return'), ('repl', 'Replacement'), ('adj', 'Adjustment')], max_length=8)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=40)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('moved_on', models.DateField(default=django.utils.timezone.localdate)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='core.station')),
                ('station_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moves_in', to='core.station')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='core.variant')),
            ],
            options={
                'ordering': ['-moved_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='core.station')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='core.variant')),
            ],
        ),
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=24, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('refund', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='core.sale')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.variant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleReplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=24, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replaces', to='core.sale')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('in_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.variant')),
                ('out_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.variant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.sale')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.variant')),
            ],
        ),
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=24, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.station')),
                ('in_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.variant')),
                ('out_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.variant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.purchase')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.variant')),
            ],
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=24, unique=True)),
                ('serial', models.CharField(blank=True, max_length=60)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('status', models.CharField(choices=[('ok', 'Active'), ('claim', 'Claimed'), ('exp', 'Expired'), ('void', 'Void')], default='ok', max_length=8)),
                ('sale_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to='core.saleline')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(max_length=240)),
                ('resolution', models.CharField(choices=[('repair', 'Repair'), ('replace', 'Replace'), ('reject', 'Reject')], default='repair', max_length=16)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('warranty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='core.warranty')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WholesalePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_tiers', to='core.product')),
            ],
            options={
                'ordering': ['min_qty'],
            },
        ),
        migrations.CreateModel(
            name='InstallmentDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('due_on', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues', to='core.installmentplan')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('plan', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_on', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.CharField(blank=True, max_length=160)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salaries', to='core.employee')),
            ],
            options={
                'unique_together': {('employee', 'period')},
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sold_on', 'status'], name='core_sale_sold_on_0d5855_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['number'], name='core_sale_number_9f59c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('product', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='stockbalance',
            unique_together={('variant', 'station')},
        ),
        migrations.AlterUniqueTogether(
            name='wholesaleprice',
            unique_together={('product', 'min_qty')},
        ),
    ]
